version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - staticcheck
    - ineffassign
    - misspell
    - govet
    - unused
    - gosec
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/phaedrus/overmind
