version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - staticcheck
    - ineffassign
    - misspell
    - govet
    - unused
    - gosec

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/phaedrus/overmind

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
